### ISSUE TITLE
The ConceptDescription  information filled in the AASX is missing when exported in JSON format

### ISSUE THREAD

**Issue by A-li-cia** [admin-shell-io/aasx-package-explorer#667] opened 2023-11-22 13:40 UTC
**Describe the bug**
I added multiple pieces of information (value, unit, description in three languages) to the “ConceptDescription” category in AAS. However, whether exporting to a JSON file or querying via URL, the returned data does not include the information within the red-marked area.

**Expected behavior**
Where can I add information such as units or symbols? Looking forward to a reply, thanks!:)

**Screenshots**
![ce9ab114b93b537dd5a70b9033d6961](https://github.com/admin-shell-io/aasx-package-explorer/assets/74972234/7fc58364-3c5e-4023-a697-79b4828ca20b)

**Comment by mhrimaz** [comment] 2023-11-22 17:52
First this is version 2, please consider use version 3 of the metamodel to avoid any migration problem.

Second, by design, the information that you write won't be inside submodel. They will be stored at a different place. Only the id of the concept description (which you marked as black) will be there. The reason that you don't see it is that you probably used the export submodel to json which only has submodel information.

if you want the whole environment then you should use the `save as ` function and specify json format:
![image](https://github.com/admin-shell-io/aasx-package-explorer/assets/17963017/d2c8cce6-b754-4d56-8669-66d753d05efe)


Then you will get the json of your whole aas. in `submodels` you will have only a reference to the concept description id. then look at the `conceptDescription` array and find your concept. You will find the unit,... there. the same principle holds when you deal with REST API.
![image](https://github.com/admin-shell-io/aasx-package-explorer/assets/17963017/5d8874ca-b70f-4bf3-8cef-d4f97001d334)

**Closed** 2024-02-08 12:31 UTC
