### ISSUE TITLE
AAS JSON export does not comply with Schema v2.0.0 or v2.0.1

### ISSUE THREAD

**Issue by heldic** [admin-shell-io/aasx-package-explorer#230] opened 2020-10-09 11:24 UTC
Hi, thanks for the work and effort put into this project!!

We tried to export a AAS Submodel to JSON file and found the folowing under `semanticId`:

```
"semanticId": {
    "keys": [
      {
        "type": "GlobalReference",
        "local": false,
        "value": "0173-1#01-ADN198#009",
        "index": 0,
        "idType": "IRDI"
      }
    ],
    "First": {
      "type": "GlobalReference",
      "local": false,
      "value": "0173-1#01-ADN198#009",
      "index": 0,
      "idType": "IRDI"
    },
    "Last": {
      "type": "GlobalReference",
      "local": false,
      "value": "0173-1#01-ADN198#009",
      "index": 0,
      "idType": "IRDI"
    }
  },
```

We'd expect:
```
"semanticId": {
    "keys": [
      {
        "type": "GlobalReference",
        "local": false,
        "value": "0173-1#01-ADN198#009",
        "idType": "IRDI"
      }
    ]
  },
```

Based on JSON Schema definition (v2.0.1):
```
    "Reference": {
      "type": "object",
      "properties": {
        "keys": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Key"
          }
        }
      },
      "required": [
        "keys"
      ]
    },
```

Issue found using the Explorer (aasx-package-explorer.2020-09-16.alpha) in Windows VM on Mac. Imported Sample AASX, selected submodel, clicked on File > Export > Export Submodel to JSON.

**Comment by MichaelHoffmeisterFesto** [comment] 2020-10-29 20:20
Hello!
Thank you a lot for reporting this! This was a clear bug, caused by adding Getter to a class which is serialized. So we fixed it, integrated to master and created a new release.

I took to the opportunity to check if the JSON serialization is correct. Appearantly, it is. I've executed test for validation on the test-samples and all produced JSON files were validated OK.

If you want to test yourself, you can use the AasxToolkit for this:
.\AasxToolkit.exe load ..\..\..\..\sample-aasx\01_Festo.aasx check+fix save test.json validate .\test.json | more

The ValidateSampleAAS.ps1 executes this for all sample files.

I will close the issue; however it would be great if you would test it and eventually re-open it.

Thanks a lot,
Michael

**Closed by MichaelHoffmeisterFesto** 2020-10-29 20:20 UTC
